// Generated by CoffeeScript 1.12.4

/* Goodreads - Handles all connectivity to Goodreads API */


/* API Docs: http://www.goodreads.com/api */

(function() {
  var Goodreads, http, oauth, querystring, utils, xml2js;

  http = require('http');

  xml2js = require('xml2js');

  oauth = (require('oauth')).OAuth;

  utils = require('utils');

  querystring = require('querystring');

  Goodreads = (function() {

    /* CONFIG */
    var clone;

    function Goodreads(config) {
      this.options = {
        host: 'www.goodreads.com',
        port: 80,
        key: config.key,
        secret: config.secret,
        callback: config.callback || 'http://localhost:3000/callback',
        method: 'GET',
        path: '',
        oauth_request_url: 'https://goodreads.com/oauth/request_token',
        oauth_access_url: 'https://goodreads.com/oauth/access_token',
        oauth_version: '1.0A',
        oauth_encryption: 'HMAC-SHA1'
      };
      this.oauthAccessToken = '';
      this.oauthAcessTokenSecret = '';
      this.client = null;
    }

    Goodreads.prototype.configure = function(gr_key, gr_secret, gr_callback) {
      this.options.key = gr_key || this.options.key;
      this.options.secret = gr_secret || this.options.secret;
      return this.options.callback = gr_callback || this.options.callback;
    };


    /* USER */

    Goodreads.prototype.showUser = function(username, callback) {
      this.options.path = "https://www.goodreads.com/user/show.xml?key=" + this.options.key + "&username=" + username;
      return this.getRequest(callback);
    };


    /* AUTHORS AND SERIES LIST OF BOOKS */

    Goodreads.prototype.getAuthor = function(authorId, page, callback) {
      this.options.path = 'https://www.goodreads.com/author/list/' + authorId + "?key=" + this.options.key + '&page=' + page;
      return this.getRequest(callback);
    };

    Goodreads.prototype.getSeries = function(seriesId, callback) {
      this.options.path = 'https://www.goodreads.com/series/' + seriesId + "?key=" + this.options.key;
      return this.getRequest(callback);
    };


    /* BOOKSHELVES */

    Goodreads.prototype.getShelves = function(userId, callback) {
      this.options.path = 'http://www.goodreads.com/shelf/list.xml?user_id=' + userId + "&key=" + this.options.key;
      return this.getRequest(callback);
    };

    Goodreads.prototype.getSingleShelf = function(shelfOptions, callback) {
      var queryOptions, userID;
      shelfOptions.key = this.options.key;
      userID = shelfOptions.userID;
      delete shelfOptions.userID;
      if ("accessToken" in shelfOptions) {
        this.oauthAccessToken = shelfOptions.accessToken;
        this.oauthAcessTokenSecret = shelfOptions.accessTokenSecret;
        delete shelfOptions.accessToken;
        delete shelfOptions.accessTokenSecret;
      }
      queryOptions = querystring.stringify(shelfOptions);
      this.options.path = 'http://www.goodreads.com/review/list/' + userID + '.xml?' + querystring.stringify(shelfOptions);
      if (this.oauthAccessToken) {
        return this.getProtectedRequest(function(result) {
          return callback(result.books[0].book);
        });
      } else {
        return this.getRequest(function(result) {
          return callback(result.GoodreadsResponse.books[0].book);
        });
      }
    };

    Goodreads.prototype.getFriends = function(userId, accessToken, accessTokenSecret, callback) {
      this.options.path = 'http://www.goodreads.com/friend/user/' + userId + '?format=xml';
      this.oauthAccessToken = accessToken;
      this.oauthAcessTokenSecret = accessTokenSecret;
      return this.getProtectedRequest(function(result) {
        return callback(result.friends[0].user);
      });
    };


    /* Search */

    Goodreads.prototype.searchBooks = function(q, callback) {
      this.options.path = "https://www.goodreads.com/search/index.xml?key=" + this.options.key + "&q=" + (encodeURI(q));
      return this.getRequest(callback);
    };


    /* OAUTH */

    Goodreads.prototype.requestToken = function(callback) {
      var oa;
      oa = new oauth(this.options.oauth_request_url, this.options.oauth_access_url, this.options.key, this.options.secret, this.options.oauth_version, this.options.callback, this.options.oauth_encryption);
      return oa.getOAuthRequestToken(function(error, oauthToken, oauthTokenSecret, results) {
        var url;
        if (error) {
          console.log(error);
          return callback('Error getting OAuth request token : ' + JSON.stringify(error), 500);
        } else {
          url = 'https://goodreads.com/oauth/authorize?oauth_token=' + oauthToken + '&oauth_callback=' + oa._authorize_callback;
          return callback({
            oauthToken: oauthToken,
            oauthTokenSecret: oauthTokenSecret,
            url: url
          });
        }
      });
    };

    Goodreads.prototype.processCallback = function(oauthToken, oauthTokenSecret, authorize, callback) {
      var oa;
      oa = new oauth(this.options.oauth_request_url, this.options.oauth_access_url, this.options.key, this.options.secret, this.options.oauth_version, this.options.callback, this.options.oauth_encryption);
      return oa.getOAuthAccessToken(oauthToken, oauthTokenSecret, authorize, function(error, oauthAccessToken, oauthAccessTokenSecret, results) {
        var parser;
        parser = new xml2js.Parser();
        if (error) {
          callback('Error getting OAuth access token : ' + (utils.inspect(error)) + '[' + oauthAccessToken + '] [' + oauthAccessTokenSecret + '] [' + (utils.inspect(results)) + ']', 500);
        } else {
          oa.get('http://www.goodreads.com/api/auth_user', oauthAccessToken, oauthAccessTokenSecret, function(error, data, response) {
            if (error) {
              return callback('Error getting User ID : ' + (utils.inspect(error)), 500);
            } else {
              return parser.parseString(data);
            }
          });
        }
        return parser.on('end', function(result) {
          result = result.GoodreadsResponse;
          if (result.user[0]['$'].id !== null) {
            return callback({
              'username': result.user[0].name[0],
              'userid': result.user[0]['$'].id,
              'success': 1,
              'accessToken': oauthAccessToken,
              'accessTokenSecret': oauthAccessTokenSecret
            });
          } else {
            return callback('Error: Invalid XML response received from Goodreads', 500);
          }
        });
      });
    };

    Goodreads.prototype.showAuthUser = function(accessToken, accessTokenSecret, callback) {
      var oa, parser;
      oa = new oauth(this.options.oauth_request_url, this.options.oauth_access_url, this.options.key, this.options.secret, this.options.oauth_version, this.options.callback, this.options.oauth_encryption);
      parser = new xml2js.Parser();
      oa.get("http://www.goodreads.com/api/auth_user", accessToken, accessTokenSecret, function(error, data, response) {
        if (error) {
          return callback('Error getting OAuth request token : ' + JSON.stringify(error), 500);
        } else {
          return parser.parseString(data);
        }
      });
      return parser.on('end', function(result) {
        result = result.GoodreadsResponse;
        if (result.user[0] !== null) {
          return callback(result.user[0]);
        } else {
          return callback('Error: Invalid XML response received from Goodreads', 500);
        }
      });
    };


    /* API: 'GET' */

    Goodreads.prototype.getRequest = function(callback) {
      var _options, parser, tmp;
      _options = this.options;
      tmp = [];
      parser = new xml2js.Parser();
      return http.request(_options, function(res) {
        res.setEncoding('utf8');
        res.on('data', function(chunk) {
          return tmp.push(chunk);
        });
        res.on('end', function(e) {
          var body;
          body = tmp.join('');
          return parser.parseString(body);
        });
        return parser.on('end', function(result) {
          return callback(result);
        });
      }).end();
    };

    Goodreads.prototype.getProtectedRequest = function(callback) {
      var oa, parser;
      oa = new oauth(this.options.oauth_request_url, this.options.oauth_access_url, this.options.key, this.options.secret, this.options.oauth_version, this.options.callback, this.options.oauth_encryption);
      parser = new xml2js.Parser();
      oa.get(this.options.path, this.oauthAccessToken, this.oauthAcessTokenSecret, function(error, data, response) {
        if (error) {
          return callback('Error getting OAuth request token : ' + JSON.stringify(error), 500);
        } else {
          return parser.parseString(data);
        }
      });
      return parser.on('end', function(result) {
        result = result.GoodreadsResponse;
        if (result !== null) {
          return callback(result);
        } else {
          return callback('Error: Invalid XML response received from Goodreads', 500);
        }
      });
    };

    clone = function(obj) {
      if (obj !== null || typeof obj !== 'object') {
        return obj;
      }
    };

    return Goodreads;

  })();

  module.exports = {
    client: function(options) {
      return new Goodreads(options);
    }
  };

}).call(this);
